In [1]:
import torch
from torch import nn
import torch.nn.functional as F

In [63]:
rDelt = pow(2,8)
TYPE = torch.int32
fc1 = nn.Linear(2,3)
fc2 = nn.Linear(3,1)

In [64]:
a = torch.Tensor([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])
#print fc1(a)
delt = pow(2,8)
fc1.weight.data, fc1.bias.data = (fc1.weight * rDelt).to(TYPE), (fc1.bias*rDelt*rDelt).to(TYPE)
#print fc1((a*rDelt).to(TYPE)).to(torch.float32)/rDelt/rDelt

In [65]:
lol = net.state_dict()
fc1.weight.data = (lol["fc1.weight"]*rDelt).to(TYPE)
fc1.bias.data = (lol["fc1.bias"]*rDelt*rDelt).to(TYPE)
fc2.weight.data = (lol["fc2.weight"]*rDelt).to(TYPE)
fc2.bias.data = (lol["fc2.bias"]*rDelt*rDelt).to(TYPE)

In [66]:
a = torch.Tensor([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])
b = torch.Tensor([0,1,1,0])

In [74]:
import time
inputs = (a*rDelt).to(TYPE)
o = F.relu(torch.from_numpy(fc1((inputs)).detach().numpy() >>8))
o = fc2(o)/rDelt
print o.to(torch.float32)/rDelt
sT = time.time()
for _ in range(100000):
    o = F.relu(fc1((inputs)))/rDelt
    o = fc2(o).div(rDelt)
eT = time.time()
print sT - eT
sT = time.time()
for _ in range(100000):
    o = F.relu(fc1((inputs)))>>8
    o = fc2(o)>>8
eT = time.time()
print sT - eT
print o.to(torch.float32)/rDelt
sT = time.time()
for _ in range(100000):
    net(af)
eT = time.time()
print sT - eT

tensor([[0.0039],
        [0.9961],
        [1.0000],
        [0.0039]], grad_fn=<DivBackward0>)
-8.56030201912
-8.12533903122
tensor([[0.0039],
        [0.9961],
        [1.0000],
        [0.0039]])
-8.07516407967


In [97]:
optim = torch.optim.SGD([
    {'params':fc1.weight},
    {'params':fc1.bias},
    {'params':fc2.weight},
    {'params':fc2.bias}
],lr = 1,momentum=0.9)
criterion = nn.MSELoss()

In [99]:
for _ in range(1):
    tLoss = 0
    for i in range(4):
        optim.zero_grad()
        o = fc1(a[i])
        o = fc2(o)
        loss = (o - b[i]).pow(torch.Tensor(([2])).to(torch.int16))
        loss.backward()
        optim.step()
        tLoss += loss.item()
    print tLoss
    print fc1.weight

911.189260341
Parameter containing:
tensor([[-213.4981, -215.0359],
        [-137.6702, -141.7028],
        [ -58.4695,  -65.8382]], requires_grad=True)


In [7]:
print torch.Tensor(([2])).to(torch.int16).pow(torch.Tensor(([2])).to(torch.int16))

tensor([4], dtype=torch.int16)


In [5]:
af = torch.Tensor([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])
bf = torch.Tensor([0,1,1,0])

In [28]:
class float_Net(nn.Module):
    def __init__(self):
        super(float_Net, self).__init__()
        self.fc1 = nn.Linear(2, 3)
        self.fc2 = nn.Linear(3, 1)

    def forward(self, x):
        
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

net = float_Net()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [31]:
for i in range(500):
    tLoss = 0
    for j in range(4):
        inputs, labels = af[j], bf[j]
        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        tLoss += loss.item()
    if i%100 == 0:
        print tLoss

9.00457262105e-05
2.36419889461e-05
6.11210401757e-06
1.6168204553e-06
4.17396467611e-07


In [33]:
print net(af)

tensor([[0.0002],
        [0.9997],
        [0.9999],
        [0.0001]], grad_fn=<ThAddmmBackward>)


In [73]:
print lol.weight

Parameter containing:
tensor([[ 31, -77],
        [-22, 160],
        [166,  58]], dtype=torch.int32, requires_grad=True)


In [77]:
a = torch.Tensor([1, 1])
w = torch.Tensor([[3], [4]])
b = torch.Tensor([0.8])
c = a.matmul(w)
print c - b

tensor([6.2000])


In [83]:
aS = a*delt
wS = w*delt
bS = b*delt*delt
c = aS.matmul(wS)
print aS, wS, (c - bS)/delt/delt

tensor([256., 256.]) tensor([[ 768.],
        [1024.]]) tensor([6.2000])


In [67]:
print 7*256*256

458752


In [68]:
256*768+256*1024

458752

In [16]:
import numpy as np
ppnp = af.numpy()
print ppnp

[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]


In [21]:
ppnp = 4*af
ppnp = ppnp >> 1
print ppnp

tensor([[0., 0.],
        [0., 2.],
        [2., 0.],
        [2., 2.]])


In [48]:
print torch.Tensor([-26613]).to(TYPE).numpy() >> 8
print int(-26613) >> 8

[-104]
-104


In [46]:
print np.int16(-23423) >> 8

-92
