In [1]:
import torch
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import PIL
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import Sample_AlexNet as Sample_AlexNet
from SampleNN import *
from tqdm import tqdm_notebook
%matplotlib inline
#device = torch.device("cuda:2" if torch.cuda.is_available() else "cpu")
device = torch.device("cpu")
import torchvision

In [2]:
import torchvision.transforms as transforms
traindir = '/home/yanzy/data/train'
valdir = '/home/yanzy/data/val'
normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])

val_loader = torch.utils.data.DataLoader(
        torchvision.datasets.ImageFolder(valdir, transforms.Compose([
            transforms.Resize(256),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            normalize,

        ])),
        batch_size=1, shuffle=False,
        num_workers=4, pin_memory=True)

In [3]:
def val(Sample = 1, N = 16, m = 8):
    TMP = protectStateDict(sample_net)
    sampleStateDict(sample_net, N, m)
    sample_net.eval()
    correct = 0
    total = 0
    count = 0
    with torch.no_grad():
        i = 0
        for data in tqdm_notebook(val_loader, desc = "m = %d"%(m), leave = False):
            if i == 82:
                images, labels = data
                images, labels = images.to(device), labels.to(device)
                images = mSample(N=N,m=m)(images)
                ttt = torch.zeros(1,3,227,227)
                ttt[:,:,2:226,2:226] = images
                img = ttt.to(device)
                outputs = sample_net(img)
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()
                #print outputs*pow(2,m)
                break
            i = i+1

    print('When m = %d, Accuracy of the network on the %d test images: %.3f %%' % (m, total,
        100.0 * correct / total))
    
    sample_net.load_state_dict(TMP)
    del TMP
    return 100.0 * correct / total, img

In [4]:
def val_float(Sample = 1, N = 16, m = 8):
    float_net.eval()
    correct = 0
    total = 0
    count = 0
    with torch.no_grad():
        for data in tqdm_notebook(val_loader, desc = "m = %d"%(m), leave = False):
                images, labels = data
                images, labels = images.to(device), labels.to(device)
                outputs = float_net(images)
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)

                correct += (predicted == labels).sum().item()
                #print correct, total
                break

    print('When m = %d, Accuracy of the network on the %d test images: %.3f %%' % (m, total,
        100.0 * correct / total))
    
    return 100.0 * correct / total

## With Clamp version

In [5]:
float_net = torchvision.models.alexnet(pretrained=True).to(device)
gt  = float_net.state_dict()
b = gt.keys()
N = 16
m = 8

In [6]:
sample_net = Sample_AlexNet.alexnet().to(device)
lol = sample_net.state_dict()
a = lol.keys()
for i in range(len(a)):
    lol[a[i]] = gt[b[i]]
    print (lol[a[i]].shape)
sample_net.load_state_dict(lol)
sampleStateDict(sample_net, N, m)
sample_net.eval()
print (len(a))

torch.Size([64, 3, 11, 11])
torch.Size([64])
torch.Size([192, 64, 5, 5])
torch.Size([192])
torch.Size([384, 192, 3, 3])
torch.Size([384])
torch.Size([256, 384, 3, 3])
torch.Size([256])
torch.Size([256, 256, 3, 3])
torch.Size([256])
torch.Size([4096, 9216])
torch.Size([4096])
torch.Size([4096, 4096])
torch.Size([4096])
torch.Size([1000, 4096])
torch.Size([1000])
16


In [8]:
sample_net.eval()
res, images = val(1,N,8)
print 'sdfsdf'

SEJveChjaGlsZHJlbj0oSW50UHJvZ3Jlc3ModmFsdWU9MCwgZGVzY3JpcHRpb249dSdtID0gOCcsIG1heD01MDAwMCwgc3R5bGU9UHJvZ3Jlc3NTdHlsZShkZXNjcmlwdGlvbl93aWR0aD11J2nigKY=


When m = 8, Accuracy of the network on the 1 test images: 100.000 %
sdfsdf


In [24]:
val_float()

SEJveChjaGlsZHJlbj0oSW50UHJvZ3Jlc3ModmFsdWU9MCwgZGVzY3JpcHRpb249dSdtID0gOCcsIG1heD01MDAwMCwgc3R5bGU9UHJvZ3Jlc3NTdHlsZShkZXNjcmlwdGlvbl93aWR0aD11J2nigKY=


When m = 8, Accuracy of the network on the 1 test images: 100.000 %


100.0

In [8]:
import time
happysfsd = 0
with torch.no_grad():
    for data in tqdm_notebook(val_loader, desc = "m = %d"%(m), leave = False):
            images, labels = data
            if labels == 23:
                happysfsd = happysfsd + 1
            if happysfsd == 13:
                break

SEJveChjaGlsZHJlbj0oSW50UHJvZ3Jlc3ModmFsdWU9MCwgZGVzY3JpcHRpb249dSdtID0gOCcsIG1heD01MDAwMCwgc3R5bGU9UHJvZ3Jlc3NTdHlsZShkZXNjcmlwdGlvbl93aWR0aD11J2nigKY=


In [8]:
print torch.max(sample_net(mSample(N=16,m=8)(images).to(device)).data, 1)
print labels

(tensor([14.3750], device='cuda:0'), tensor([138], device='cuda:0'))
tensor([23])


In [76]:
M = (images.to(torch.float32)/pow(2,-8)).round().clamp(-pow(2,16),pow(2,16)-1).to(torch.int32)


In [8]:
a = torch.load('./Weights/features.0.weight.pt')
print(a.size())

torch.Size([64, 3, 11, 11])


In [11]:
N = 16
m = 8
delt = pow(2,-m)
Q = pow(2, N-1) - 1
ImageSize = 224
img = torchvision.transforms.ToTensor()(plt.imread('timg.jpg'))
img = nn.functional.interpolate(img.view(1,3,650,1200),size=(ImageSize,ImageSize),mode='bilinear')
img = (img/delt).to(torch.int16)
img = img.to(torch.float) * delt

In [25]:
sample_net.eval()
a = open('test.csv', 'w+')
for i in list((mSample(N,m)(sample_net(img))/delt).view(-1).detach().numpy()):
    a.write('%d,'%i)

In [26]:
a.close()

In [55]:
sample_net(img).argmax()

tensor(803)

In [54]:
float_net.eval()
float_net(img).argmax()

tensor(803)

In [43]:
torchvision.transforms.ToTensor()(plt.imread('timg.jpg'))

tensor([[[0.7647, 0.7569, 0.7490,  ..., 0.6549, 0.6627, 0.6627],
         [0.7686, 0.7608, 0.7647,  ..., 0.6471, 0.6667, 0.6667],
         [0.7686, 0.7569, 0.7725,  ..., 0.6471, 0.6353, 0.6431],
         ...,
         [0.4078, 0.3804, 0.4157,  ..., 0.2706, 0.5373, 0.5882],
         [0.3922, 0.3843, 0.3843,  ..., 0.2157, 0.4471, 0.5843],
         [0.5059, 0.5176, 0.5137,  ..., 0.2078, 0.3529, 0.5255]],

        [[0.7294, 0.7255, 0.7176,  ..., 0.6549, 0.6627, 0.6627],
         [0.7333, 0.7255, 0.7294,  ..., 0.6392, 0.6588, 0.6588],
         [0.7412, 0.7294, 0.7451,  ..., 0.6392, 0.6275, 0.6353],
         ...,
         [0.2902, 0.2588, 0.2941,  ..., 0.2353, 0.4431, 0.5412],
         [0.2706, 0.2627, 0.2627,  ..., 0.2000, 0.3804, 0.5255],
         [0.4314, 0.4431, 0.4392,  ..., 0.1922, 0.2824, 0.4706]],

        [[0.6941, 0.6824, 0.6745,  ..., 0.6549, 0.6627, 0.6627],
         [0.6980, 0.6902, 0.6941,  ..., 0.6510, 0.6706, 0.6706],
         [0.7020, 0.6902, 0.7059,  ..., 0.6510, 0.6392, 0.

In [7]:
a = torch.load('conv1.pt')

In [8]:
for i in range(55):
    for j in range(55):
        print int(a[0,0,i,j])
    break

-277
-383
-427
-412
-386
-464
-483
-449
-475
-446
-417
-425
-391
-384
-370
-426
-364
-401
-450
-518
-554
-617
-1062
178
61
-289
-298
-295
-304
-254
-329
-291
-243
-214
-302
-307
-339
-348
-384
-365
-289
-245
-266
-347
-371
-323
-353
-148
43
-158
-234
-251
-204
-297
-319


In [51]:
print (images*256)[0,0,2,:]

tensor([  0.,   0., 141., 154., 146., 154., 154., 168., 168., 163., 154., 150.,
        150., 159., 168., 168., 168., 163., 168., 176., 176., 163., 172., 168.,
        154., 154., 163., 168., 163., 168., 168., 168., 168., 159., 154., 159.,
        150., 154., 159., 159., 154., 154., 163., 163., 154., 154., 163., 168.,
        168., 172., 185., 172., 172., 172., 181., 181., 176., 163., 168., 172.,
        168., 163., 176., 168., 181., 172., 163., 168., 163., 172., 176., 168.,
        168., 163., 185., 185., 185., 189., 181., 181., 189., 185., 168., 172.,
        181., 198., 194., 181., 176., 181., 198., 207., 207., 203., 185., 216.,
        189., 172., 172., 172., 172., 168., 163., 172., 172., 159., 159., 163.,
        159., 154., 150., 150., 159., 168., 163., 163., 163., 163., 150., 146.,
        124., 128., 119., 106., 111., 115., 106., 102., 111., 111., 128., 132.,
        137., 132., 150., 154., 163., 154., 163., 159., 159., 159., 163., 163.,
        168., 176., 172., 172., 172., 16

In [7]:
st = sample_net.state_dict()
st.keys()

['features.0.weight',
 'features.0.bias',
 'features.5.weight',
 'features.5.bias',
 'features.10.weight',
 'features.10.bias',
 'features.14.weight',
 'features.14.bias',
 'features.18.weight',
 'features.18.bias',
 'classifier.2.weight',
 'classifier.2.bias',
 'classifier.7.weight',
 'classifier.7.bias',
 'classifier.11.weight',
 'classifier.11.bias']

In [9]:
mSample(16,8)(st['features.0.bias'])*256

tensor([-248., -719.,   -9.,  -20.,  -30.,    6.,  -19., -363.,  421.,  -25.,
          -4.,  -33.,  -17.,   -9.,  -19., -332.,  -13.,    3.,  -26., -304.,
         -35.,  -13.,  -20.,  -10.,  -25.,  -18., -496.,  -22.,  -36.,  -50.,
         -33., -514.,  -12.,  -15.,   -9.,  -98., -712.,  169.,  -42., -545.,
          14.,   -7.,  -44.,  -15., -108., -496., -310.,    4.,  -28.,   -6.,
         -38., -474.,  -24.,   -5.,  -18.,  -15.,  -16.,  -18., -325.,  -30.,
         -11.,  -83.,   13.,   -4.])

In [10]:
conv2d = nn.Conv2d(3, 64, kernel_size=11, stride=4, padding=0)
stconv = conv2d.state_dict()
stconv['weight'] = mSample(16,8)(st['features.0.weight'])
stconv['bias'] = mSample(16,8)(st['features.0.bias'])
conv2d.load_state_dict(stconv)
(mSample(16,8)(conv2d(images))*256).to(torch.int)

tensor([[[[ -298,  -404,  -449,  ...,  -241,  -337,  -356],
          [ -255,  -308,  -332,  ...,  -340,  -358,  -352],
          [ -219,  -302,  -253,  ...,  -412,  -397,  -328],
          ...,
          [ -342,  -197,  -267,  ...,  -216,  -226,  -292],
          [ -339,  -192,  -271,  ...,  -258,  -291,  -202],
          [ -358,  -252,  -269,  ...,  -311,  -352,  -214]],

         [[-1445, -1503, -1503,  ..., -1953, -1939, -2420],
          [-1224, -1236, -1254,  ..., -1732, -1696, -2231],
          [-1209, -1199, -1224,  ..., -1713, -1721, -2227],
          ...,
          [ -430,  -477,  -479,  ...,   229,   268,   868],
          [ -406,  -452,  -448,  ...,   318,   286,   923],
          [ -355,  -394,  -396,  ...,   496,   433,  1016]],

         [[  -52,  -179,   -75,  ...,  -119,   -40,   -27],
          [  -70,   -50,   -47,  ...,   -77,  -120,   -90],
          [  -37,   -87,   -91,  ...,    22,  -134,  -152],
          ...,
          [   65,   -98,     9,  ...,   162,    31,

In [14]:
conv2d = nn.Conv2d(1, 1, kernel_size=11, stride=4, padding=0,bias=False)
stconv = conv2d.state_dict()
#st['features.0.weight'][0,2,:,:] 0- inpur channel, 2 output channel
stconv['weight'] = mSample(16,8)(st['features.0.weight'][0,2,:,:].view(1,1,11,11))
conv2d.load_state_dict(stconv)
#conv2d(images[0,0,:,:] 00 - input 0, 01 input 1, 02 input 2
(mSample(16,8)(conv2d(images[0,0,:,:].view(1,1,227,227)))*256).to(torch.int)

tensor([[[[-28, -47, -32,  ..., -53, -66, -28],
          [ -5, -38, -48,  ..., -22, -53, -25],
          [ -8, -38, -28,  ..., -52, -50, -42],
          ...,
          [ 12,  20,  26,  ...,  66, 129,  58],
          [ 14,  30,  30,  ...,  82, 144,  55],
          [-40,  -4, -40,  ...,  -1, -14, -50]]]], dtype=torch.int32)

In [16]:
t = 0
for i in range(11):
    for j in range(11):
        t += mSample(16,8)(st['features.0.weight'][0,0,i,j] * images[0,0,i,j])
        t = mSample(16,8)(t)
        print int(st['features.0.weight'][0,0,i,j]*256) , int(images[0,0,i,j]*256)
t*256

30 0
24 0
24 0
27 0
26 0
17 0
13 0
13 0
14 0
6 0
13 0
19 0
10 0
14 0
19 0
19 0
19 0
13 0
7 0
7 0
-3 0
1 0
19 0
10 0
14 142
14 155
13 146
13 155
12 155
6 168
11 168
3 164
3 155
18 0
13 0
16 150
16 146
15 146
10 159
12 150
10 159
12 164
0 168
1 159
22 0
19 0
18 142
21 137
24 142
17 146
9 155
5 159
6 155
-3 168
-9 168
25 0
25 0
26 133
28 142
19 142
9 142
-2 146
-11 150
-10 150
-15 164
-14 164
29 0
30 0
27 133
23 133
1 142
-23 146
-29 150
-36 146
-32 142
-22 159
-19 155
24 0
28 0
21 124
11 124
-15 133
-41 142
-32 142
-40 133
-42 129
-30 142
-24 150
24 0
27 0
17 115
6 111
-18 120
-47 129
-35 133
-47 124
-52 124
-33 124
-29 137
11 0
17 0
9 120
1 115
-23 124
-50 120
-63 120
-62 124
-52 129
-29 124
-27 133
12 0
16 0
6 129
-5 120
-17 124
-30 129
-36 115
-42 120
-30 124
-24 133
-21 124


tensor(-363.)

In [11]:
t*256

0