In [48]:
import torch
import torch.nn as nn
import torchvision
from matplotlib import pyplot as plt

# 这3个有用的
InChannel = 0
OutChannel = 0
# filter的文件路径，按照自己的路径调整一下吧
filterFilePath = './Weights/features.0.weight.pt'

# 这些不用改
N = 16
m = 8
delt = pow(2,-m)
Q = pow(2, N-1) - 1
intWeights = torch.load(filterFilePath)
floatWeights = intWeights*delt
conv = nn.Conv2d(1, 1, kernel_size=11, stride=4, padding=0)
state_dict = conv.state_dict()
state_dict['weight'] = floatWeights[InChannel][OutChannel].view(state_dict['weight'].size())
state_dict['bias'] = torch.zeros(state_dict['bias'].size())
conv.load_state_dict(state_dict)

In [57]:
ImageSize = 224
LargeSize = 227
img = torchvision.transforms.ToTensor()(plt.imread('timg.jpg'))
img = nn.functional.interpolate(img.view(1,3,650,1200),size=(ImageSize,ImageSize),mode='bilinear')
img = (img/delt).to(torch.int16)
img = img.to(torch.float) * delt
ttt = torch.zeros(1,3,LargeSize,LargeSize)
ttt[:,:,1:225,1:225] = img
img = ttt
output = ((conv(img[:,InChannel,:,:].view(1,1,LargeSize,LargeSize))/delt).to(torch.int16).to(torch.float) * delt).view(55,55)

In [7]:
F = open(str(InChannel) + '.' + str(OutChannel) + '.output.csv','w+')
strOutput = ''
for i in range(len(output)):
    for j in range(len(output)):
        strOutput += '%.8f, '%(output[i][j])
    strOutput += '\n'
F.write(strOutput)
F.close()

In [58]:
output4 = output

# Important Findings

Padding 2 in the front and padding 1 in the back, making an 224 x 224 image 227 x 227
is the same as padding 2 in both side to make it 228 x 228 when filter is 11 x 11

In [56]:
print (output1 != output3).sum()

tensor(0)


In [47]:
print output1

tensor([[-2.1289, -0.4492, -0.7891,  ..., -0.8945, -0.4180, -1.0195],
        [-1.3945, -0.3750,  0.5742,  ..., -0.6719,  0.2188, -0.5273],
        [-0.6562, -0.4922, -0.5312,  ..., -0.6953,  0.3320, -0.5938],
        ...,
        [-0.5586,  1.1250, -0.3438,  ..., -1.2500,  0.7031,  0.5781],
        [-0.6094,  0.2148, -0.4102,  ..., -0.9102,  0.3633,  0.9414],
        [-0.6523, -0.1016, -0.6016,  ...,  0.1797,  0.8359,  1.3281]])


In [51]:
print output2

tensor([[-2.1289, -0.4492, -0.7891,  ..., -0.8945, -0.4180, -1.0195],
        [-1.3945, -0.3750,  0.5742,  ..., -0.6719,  0.2188, -0.5273],
        [-0.6562, -0.4922, -0.5312,  ..., -0.6953,  0.3320, -0.5938],
        ...,
        [-0.5586,  1.1250, -0.3438,  ..., -1.2500,  0.7031,  0.5781],
        [-0.6094,  0.2148, -0.4102,  ..., -0.9102,  0.3633,  0.9414],
        [-0.6523, -0.1016, -0.6016,  ...,  0.1797,  0.8359,  1.3281]])


In [55]:
print output3

tensor([[-2.1289, -0.4492, -0.7891,  ..., -0.8945, -0.4180, -1.0195],
        [-1.3945, -0.3750,  0.5742,  ..., -0.6719,  0.2188, -0.5273],
        [-0.6562, -0.4922, -0.5312,  ..., -0.6953,  0.3320, -0.5938],
        ...,
        [-0.5586,  1.1250, -0.3438,  ..., -1.2500,  0.7031,  0.5781],
        [-0.6094,  0.2148, -0.4102,  ..., -0.9102,  0.3633,  0.9414],
        [-0.6523, -0.1016, -0.6016,  ...,  0.1797,  0.8359,  1.3281]])


In [59]:
print output4

tensor([[-1.2695, -0.2695, -0.1719,  ..., -0.8164, -0.2578, -0.6328],
        [-0.8750, -0.3438,  0.7422,  ..., -0.5664,  0.2070, -0.3633],
        [-0.2852, -0.5195, -0.6719,  ..., -0.3672,  0.2891, -0.4453],
        ...,
        [ 0.1523,  0.6641, -0.6328,  ..., -0.8320,  0.9414,  0.3750],
        [-0.2344,  0.0391, -0.6953,  ..., -0.6484,  0.5625,  0.9375],
        [ 0.2305,  0.4141,  0.1250,  ...,  0.8867,  1.5000,  1.4297]])
